### ISSUE TITLE
I am getting problem while running this code 

### ISSUE THREAD

**Issue by rahashwini** [koreyou/listnet_chainer#2]
Hello,
I am trying to execute your uploaded code with all required pre-requisite.
INFO:root:Loading dataset
Traceback (most recent call last):
  File "G:\Implementation of the Project\Learning to Rank Algorithms\Python\ListNet+Chainer\listnet_chainer-master\listnet_chainer-master\bin\train.py", line 51, in <module>
    run(args)
  File "G:\Implementation of the Project\Learning to Rank Algorithms\Python\ListNet+Chainer\listnet_chainer-master\listnet_chainer-master\bin\train.py", line 15, in run
    train = dataset.create_dataset(args.train)
  File "G:\Implementation of the Project\Learning to Rank Algorithms\Python\ListNet+Chainer\listnet_chainer-master\listnet_chainer-master\listnet\dataset.py", line 28, in create_dataset
    with open(path, mode='r') as fin:
FileNotFoundError: [Errno 2] No such file or directory: 'build/MQ2007/Fold1/train.txt'

Please help me to sort out this error

**Comment by rahashwini** [comment]
Yes, I directory hierarchy is same. I have also extracted the rar file that
containing MQ2007 dataset
