### ISSUE TITLE
Getting error in creat_dataset() function

### ISSUE THREAD

**Issue by rahashwini** [koreyou/listnet_chainer#3]
Traceback (most recent call last):
  File "G:\Implementation of the Project\Learning to Rank Algorithms\Python\ListNet+Chainer\listnet_chainer-master\listnet_chainer-master\bin\train.py", line 52, in <module>
    run(args)
  File "G:\Implementation of the Project\Learning to Rank Algorithms\Python\ListNet+Chainer\listnet_chainer-master\listnet_chainer-master\bin\train.py", line 16, in run
    train = dataset.create_dataset(args.train)
  File "G:\Implementation of the Project\Learning to Rank Algorithms\Python\ListNet+Chainer\listnet_chainer-master\listnet_chainer-master\listnet\dataset.py", line 43, in create_dataset
    v = np.array(d[1], dtype=np.float32)
TypeError: float() argument must be a string or a number, not 'map'

Please try to figure out what is problem in your code

**Comment by koreyou** [comment]
hi. thanks for the interest in my code.
Could you tell me the version of your python that you're running?

**Comment by koreyou** [comment]
I confirmed that this error reproduces on python 3.6.4. Could you try it out on python 2.7.12?

**Comment by rahashwini** [comment]
Ok, I will try it on Python 2.7.12. For neural network, you have used
chainer package. Have u tried it with theano?
